#!/usr/bin/env bash

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t "$1"
    else
        tmux switch-client -t "$1"
    fi
}

has_session() {
    tmux has-session -t "$1" 2>/dev/null
}

hydrate() {
    local sessionizer_path="$2/.tmux-sessionizer"
    if [ -f "$sessionizer_path" ]; then
        tmux send-keys -t "$1" "source $sessionizer_path" C-m
    elif [ -f "$HOME/.tmux-sessionizer" ]; then
        tmux send-keys -t "$1" "source $HOME/.tmux-sessionizer" C-m
    fi
}
identifier=$(hostname)
if [[ $# -eq 1 ]]; then
    selected="$1"
else
    if [[ "$identifier" == "dev.local" ]]; then
        selected=$(find ~/repos ~/repos/github.com/payzip -mindepth 3 -maxdepth 3 -type d -o -path ~/vault -prune 2>/dev/null | fzf)
    else
        selected=$(find ~/repos -mindepth 3 -maxdepth 3 -type d -o -path ~/vault -prune 2>/dev/null | fzf)
    fi
fi

[[ -z $selected ]] && exit 0

selected_name=$(basename "$selected" | tr . _)

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    hydrate "$selected_name" "$selected"
    exit 0
fi

if ! has_session "$selected_name"; then
    tmux new-session -ds "$selected_name" -c "$selected"
    hydrate "$selected_name" "$selected"
fi

switch_to "$selected_name"
